### ISSUE TITLE
How is FoxGet different from Thor Check for Updates?

### ISSUE THREAD

**Issue by Jimrnelson** [DougHennig/FoxGet#3]
Interesting to use Thor CFU to get a project that can install projects already available from CFU.

I have always been aware that little attention was paid to where components were stored when downloaded with CFU.  I don't recall comments asking for the ability to store them elsewhere than in a sub-folder of Thor.

So this is a welcome addition.

**Comment by DougHennig** [comment]
For Thor Tools, having them in a subdirectory of Thor makes perfect sense. For Components, not so much for reasons I outlined in README.md. Also, as you know, many Thor updaters install everything, including samples and documentation, rather than just the minimum set of files needed to be added to an application.
